package com.mycompany.coursemanagement.GUI;

import com.mycompany.coursemanagement.GUI.DialogChooseDepartment.DepartmentDialogListener;
import com.mycompany.coursemanagement.Models.Department;
import helper.DateTimeHelper;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;

public class PnOnsiteCourse extends javax.swing.JPanel implements DepartmentDialogListener {

    private Department department;

    public PnOnsiteCourse() {
        initComponents();
        this.department = null;
    }

    public JButton getBtnChooseDepartment() {
        return btnChooseDepartment;
    }

    public JCheckBox getCbFriday() {
        return cbFriday;
    }

    public JCheckBox getCbMonday() {
        return cbMonday;
    }

    public JCheckBox getCbSaturday() {
        return cbSaturday;
    }

    public JCheckBox getCbThursday() {
        return cbThursday;
    }

    public JCheckBox getCbTuesday() {
        return cbTuesday;
    }

    public JCheckBox getCbWednesday() {
        return cbWednesday;
    }

    public JSpinner getSpinnerTime() {
        return spinnerTime;
    }

    public JTextField getTxtCourseId() {
        return txtCourseId;
    }

    public JTextField getTxtCredits() {
        return txtCredits;
    }

    public JTextField getTxtDepartment() {
        return txtDepartment;
    }

    public JTextField getTxtLocation() {
        return txtLocation;
    }

    public JTextField getTxtTitle() {
        return txtTitle;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public void setTime(int hour, int minute) {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.HOUR_OF_DAY, hour);
        calendar.set(Calendar.MINUTE, minute);

        spinnerModel.setValue(calendar.getTime());
        spinnerTime.repaint();
    }

    public int getHour() {
        int hour = 0;
        Object value = spinnerTime.getValue();
        if (value instanceof Date) {
            Date date = (Date) value;
            LocalDateTime ldt = DateTimeHelper.convertDateObjToLDT(date);
            hour = ldt.getHour();
        }
        return hour;
    }

    public int getMinute() {
        int minute = 0;
        Object value = spinnerTime.getValue();
        if (value instanceof Date) {
            Date date = (Date) value;
            LocalDateTime ldt = DateTimeHelper.convertDateObjToLDT(date);
            minute = ldt.getMinute();
        }
        return minute;
    }

    public void clearAllInput() {
        txtCourseId.setText("");
        txtTitle.setText("");
        txtCredits.setText("");
        department = null;
        txtDepartment.setText("");
        txtLocation.setText("");
        cbMonday.setSelected(false);
        cbTuesday.setSelected(false);
        cbWednesday.setSelected(false);
        cbThursday.setSelected(false);
        cbFriday.setSelected(false);
        cbSaturday.setSelected(false);
        txtCourseId.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOnsiteCourse = new javax.swing.JLabel();
        lblCourseId = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblCredits = new javax.swing.JLabel();
        txtCredits = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        btnChooseDepartment = new javax.swing.JButton();
        lblLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lblDays = new javax.swing.JLabel();
        cbMonday = new javax.swing.JCheckBox();
        cbTuesday = new javax.swing.JCheckBox();
        cbWednesday = new javax.swing.JCheckBox();
        cbThursday = new javax.swing.JCheckBox();
        cbFriday = new javax.swing.JCheckBox();
        cbSaturday = new javax.swing.JCheckBox();
        lblTime = new javax.swing.JLabel();
        Date date = new Date();
        spinnerModel = new SpinnerDateModel();
        spinnerTime = new javax.swing.JSpinner(spinnerModel);

        setBackground(new java.awt.Color(255, 255, 255));

        lblOnsiteCourse.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblOnsiteCourse.setText("Onsite course");

        lblCourseId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblCourseId.setText("Course ID");

        txtCourseId.setEditable(false);
        txtCourseId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCourseId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblTitle.setText("Title");

        txtTitle.setEditable(false);
        txtTitle.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblCredits.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblCredits.setText("Credits");

        txtCredits.setEditable(false);
        txtCredits.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCredits.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblDepartment.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDepartment.setText("Department");

        txtDepartment.setEditable(false);
        txtDepartment.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnChooseDepartment.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnChooseDepartment.setText("Choose");
        btnChooseDepartment.setEnabled(false);
        btnChooseDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseDepartmentActionPerformed(evt);
            }
        });

        lblLocation.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblLocation.setText("Location");

        txtLocation.setEditable(false);
        txtLocation.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblDays.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDays.setText("Days");

        cbMonday.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbMonday.setText("Mon");
        cbMonday.setEnabled(false);

        cbTuesday.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbTuesday.setText("Tue");
        cbTuesday.setEnabled(false);

        cbWednesday.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbWednesday.setText("Wed");
        cbWednesday.setEnabled(false);

        cbThursday.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbThursday.setText("Thu");
        cbThursday.setEnabled(false);

        cbFriday.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbFriday.setText("Fri");
        cbFriday.setEnabled(false);

        cbSaturday.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cbSaturday.setText("Sat");
        cbSaturday.setEnabled(false);

        lblTime.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblTime.setText("Time");

        spinnerTime.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        spinnerTime.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOnsiteCourse)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDepartment)
                            .addComponent(lblCourseId)
                            .addComponent(lblTitle)
                            .addComponent(lblCredits)
                            .addComponent(lblLocation)
                            .addComponent(lblDays)
                            .addComponent(lblTime))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChooseDepartment))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbMonday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTuesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbWednesday))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(spinnerTime, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbThursday)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbFriday)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbSaturday))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOnsiteCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartment)
                    .addComponent(btnChooseDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMonday)
                    .addComponent(cbTuesday)
                    .addComponent(cbWednesday)
                    .addComponent(lblDays))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbThursday)
                    .addComponent(cbFriday)
                    .addComponent(cbSaturday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerTime, "HH:mm");
        spinnerTime.setEditor(editor);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseDepartmentActionPerformed
        // TODO add your handling code here:
        DialogChooseDepartment dialog = new DialogChooseDepartment((JDialog) javax.swing.SwingUtilities.getWindowAncestor(this), true);
        dialog.setListener(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnChooseDepartmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseDepartment;
    private javax.swing.JCheckBox cbFriday;
    private javax.swing.JCheckBox cbMonday;
    private javax.swing.JCheckBox cbSaturday;
    private javax.swing.JCheckBox cbThursday;
    private javax.swing.JCheckBox cbTuesday;
    private javax.swing.JCheckBox cbWednesday;
    private javax.swing.JLabel lblCourseId;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblDays;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblOnsiteCourse;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private SpinnerModel spinnerModel;
    private javax.swing.JSpinner spinnerTime;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onDepartmentChosen(Department department) {
        setDepartment(department);
        txtDepartment.setText(department.getName());
    }
}
