package com.mycompany.coursemanagement.GUI;

import com.mycompany.coursemanagement.GUI.DialogChooseDepartment.DepartmentDialogListener;
import com.mycompany.coursemanagement.Models.Department;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTextField;

public class PnOnlineCourse extends javax.swing.JPanel implements DepartmentDialogListener {

    private Department department;

    public PnOnlineCourse() {
        initComponents();
        this.department = null;
    }

    public JButton getBtnChooseDepartment() {
        return btnChooseDepartment;
    }

    public JTextField getTxtCourseId() {
        return txtCourseId;
    }

    public JTextField getTxtCredits() {
        return txtCredits;
    }

    public JTextField getTxtDepartment() {
        return txtDepartment;
    }

    public JTextField getTxtTitle() {
        return txtTitle;
    }

    public JTextField getTxtUrl() {
        return txtUrl;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public void clearAllInput() {
        txtCourseId.setText("");
        txtTitle.setText("");
        txtCredits.setText("");
        department = null;
        txtDepartment.setText("");
        txtUrl.setText("");
        txtCourseId.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOnlineCourse = new javax.swing.JLabel();
        lblCourseId = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblCredits = new javax.swing.JLabel();
        txtCredits = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        btnChooseDepartment = new javax.swing.JButton();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOnlineCourse.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblOnlineCourse.setText("Online course");
        add(lblOnlineCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblCourseId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblCourseId.setText("Course ID");
        add(lblCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, -1, -1));

        txtCourseId.setEditable(false);
        txtCourseId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCourseId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(txtCourseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 40, 260, 30));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblTitle.setText("Title");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, -1, -1));

        txtTitle.setEditable(false);
        txtTitle.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 82, 260, 30));

        lblCredits.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblCredits.setText("Credits");
        add(lblCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, -1, -1));

        txtCredits.setEditable(false);
        txtCredits.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtCredits.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(txtCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 124, 260, 30));

        lblDepartment.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDepartment.setText("Department");
        add(lblDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 171, -1, -1));

        txtDepartment.setEditable(false);
        txtDepartment.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 166, 260, 30));

        btnChooseDepartment.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnChooseDepartment.setText("Choose");
        btnChooseDepartment.setEnabled(false);
        btnChooseDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseDepartmentActionPerformed(evt);
            }
        });
        add(btnChooseDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 168, -1, -1));

        lblUrl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblUrl.setText("URL");
        add(lblUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, -1, -1));

        txtUrl.setEditable(false);
        txtUrl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtUrl.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(txtUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 208, 388, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseDepartmentActionPerformed
        // TODO add your handling code here:
        DialogChooseDepartment dialog = new DialogChooseDepartment((JDialog) javax.swing.SwingUtilities.getWindowAncestor(this), true);
        dialog.setListener(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnChooseDepartmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseDepartment;
    private javax.swing.JLabel lblCourseId;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblOnlineCourse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onDepartmentChosen(Department department) {
        setDepartment(department);
        txtDepartment.setText(department.getName());
    }
}
